version: "3.8"

services:
  mysql:
#    image: mysql:8.0
    image: arm64v8/mysql:8.0-oracle
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fastfood
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data: